apiVersion: v1
kind: Service
metadata:
  labels:
    app: ServiceBusTopicMessagesConsumer
  name: ServiceBusTopicMessagesConsumer
  namespace: default
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 6443
  selector:
    app: ServiceBusTopicMessagesConsumer
    app: ServiceBusTopicMessagesConsumer
  sessionAffinity: None
  type: LoadBalancer 
